version: "3.9"

services:
  web:
    image: accounts-frontend:${ACCOUNT_FRONTEND_TAG}
    depends_on:
      - accounts
    ports:
      - "8088:80"

  accounts:
    depends_on:
      - mysql
    image: accounts:v1.0.0
    ports:
      - "8081:80"
    volumes:
      - ./config:/config
    restart: always

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}


  db-migration:
    image: goose
    working_dir: /migrations
    volumes:
      - ./src/database/migrations:/migrations
    command: 'goose status'
    depends_on:
      - mysql
    environment:
      GOOSE_DRIVER: mysql
      GOOSE_DBSTRING: root:${MYSQL_PASSWORD}@tcp(mysql)/${MYSQL_DB}
volumes:
  mysql:
  #external: true
