FROM golang:1.15-alpine as build-stage

RUN apk --update upgrade \
    && apk --no-cache --no-progress add git mercurial bash gcc musl-dev curl tar ca-certificates tzdata \
    && update-ca-certificates \
    && rm -rf /var/cache/apk/*

WORKDIR /accounts

COPY go.mod .
COPY go.sum .
RUN GO111MODULE=on GOPROXY=https://goproxy.cn go mod download

COPY . .

RUN script/make.sh

FROM scratch
COPY --from=build-stage /accounts/dist/accounts /
EXPOSE 80
VOLUME ["/config"]
ENTRYPOINT ["/accounts"]
