version: "3.9"

services:
  web:
    image: ${ACCOUNT_FRONTEND_IMAGE}
    depends_on:
      - accounts
    ports:
      - "8088:80"

  accounts:
    depends_on:
      - mysql
    image: ${ACCOUNT_IMAGE}
    ports:
      - "8081:80"
    configs:
      - source: prod_config
        target: /config/dev.yaml
        mode: 0440
    restart: always
    command: go run src/server/main.go

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    command: --character-set-server=utf8mb4 --default-time-zone=+08:00

  #  db-creation:
  #    image: mysql:5.7
  #    command: mysql -uroot -p$MYSQL_PASSWORD -hmysql -e "CREATE SCHEMA $MYSQL_DB DEFAULT CHARACTER SET utf8mb4"
  #    depends_on:
  #      - mysql

  db-migration:
    image: goose
    depends_on:
      - mysql
    working_dir: /migrations
    volumes:
      - ./src/database/migrations:/migrations
    command: goose up
    environment:
      GOOSE_DRIVER: mysql
      GOOSE_DBSTRING: root:${MYSQL_PASSWORD}@tcp(mysql)/${MYSQL_DB}
volumes:
  mysql:
  #external: true

configs:
  prod_config:
    file: ./config/dev.yaml
