apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  plain.yaml: |
    server:
      port: {{ required "A valid .Values.api.server.port required" .Values.api.server.port }}
    locale: {{ .Values.api.locale }}
  secret.yaml: |-
    database:
      {{- .Values.mysql.auth | toYaml | nindent 6 }}