apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  plain.yaml: |
    server:
      port: 80
    locale: zh-CN
  secret.yaml: |-
    database:
      {{- .Values.mysql.auth | toYaml | nindent 6 }}
