apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "api.labels" . | nindent 4}}
spec:
  ports:
    - port: {{ required "A valid .Values.api.server.port required" .Values.api.server.port }}
  selector:
    {{- include "api.selectorLabels" . |nindent 6}}
