apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    {{- include "mysql.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . |nindent 6}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "mysql.selectorLabels" . |nindent 8}}
    spec:
      containers:
        - image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag | default .Chart.AppVersion }}"
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
          ports:
            - containerPort: 3306
              name: mysql
          args: ["--character-set-server=utf8mb4","--default-time-zone=+08:00","--ignore-db-dir=lost+found"]
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
