apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  {{- with .Values.mysql.auth }}
  host: {{ .host | quote }}
  username: {{ .username | quote }}
  password: {{ .password | quote }}
  database: {{ .schema | quote }}
  port: {{ .port | quote }}
  {{- end }}