apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "web.labels" . | nindent 4}}
spec:
  ports:
    - port: {{ required "A valid .Values.web.port required" .Values.web.port }}
  selector:
    {{- include "web.selectorLabels" . |nindent 6}}
  type: NodePort
