apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: bitmyth/goose:v1.0.0
          command: ["goose",  "up"]
          workingDir: /migrations
          env:
            - name: GOOSE_DRIVER
              value: mysql
            - name: GOOSE_DBSTRING
              value: root:123@tcp(mysql)/accounts
          volumeMounts:
            - name: migration
              mountPath: /migrations
      restartPolicy: Never
      initContainers:
        - name: wait-db
          image: busybox:1.28
          command: ['sh', '-c', "until telnet mysql 3306; do echo waiting for mysql; sleep 1; done"]
      volumes:
        - name: migration
          configMap:
            name: migration
  backoffLimit: 4
