rsa:
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAwEBqQSDM23+SvEpDnGCl2i1KTZOaNT4PWfgMtRVmY//+Y6mL
    HtWmM0Cafa1OA1gfcR0IklnV4YeT8upl4J8viRtO7ZB3X6XfsLQrJIo4qtkdkKNL
    yGx+8q9wbvydvPGNQrddyaHrfkROwHEqubXSmaLZ4dWXUqTQcYB+3XO+Iy5E5G53
    o0hn+wAKNPV27Ty3ZHd8997L2L0Fd3Pl+N5TliqtGzJKas2Z8sqBiNWKk9iWNM00
    vWL+t+OrrezUfHOOPnjMN1jBL32bHz15iaAgkMh6XbJMD1eeOsvezUBlKvPqBX+I
    NAxLMIr/8Kqb6vmXIslProldS3nGaRkWjQ9spwIDAQABAoIBAGivKqyIFcS39Mi+
    j45JOkZRPxJ6+w9e2bEd1p2MJ5LwRC80lOKXZ8akuPsSMVa013oaWx6F+Ga0EqXF
    aPAk/hdkXVgSwE2+3s0zbgKZmT2+t9CYep2KJp4zVb+5opLN3SOlAVbX6ol43IEB
    nkg9b43lFUtZqOqBgFctpucjLTet+G5RkLoOzcgFUc9JgR/IE1b7tmDJmcTNb1cp
    G/YP+/MYOKL7P0vm3iBDk4Hmmo7+mqei+qfSECzOgQkinUJzhTFWwfhAgL5aR6xd
    ZG3eCiBEDQi74CxNVL4z5A5zVJXS96YIx0wlEttDT00uVtaXNr8EllTCIE6QUXRi
    8aArRFECgYEA/U9glgfDxv0EuCRTinErYQyFYCboAxhDmEw4ObyiFn1VI5O1t8+s
    B9w//aPLUQvnULrEJPPVp49LEGK0qqUIis+jtSG1HVIsuI/S/+mbT6RlYsd69Kjs
    0v4aH2LzQRQZxaPZNptBCWvtoGsDJrMcLNTzDkXeJOiaK7ivqsXg5n0CgYEAwksM
    8PKRIGe2wXfH10UfgSJWIfLz+4KK3y7fxRdDNh3Punz4iCrN8I6sdnR4QFlRzY9J
    VfRcB1LYH59EzPaeMWj6oLnTua5DfAAqCQ+b9zMwpt5Gxc0/jsuEjTnIb03goYMP
    xtKRcbbpbKkm7x8AJAAUOfefZ5zgF4jpIHX0dPMCgYEAmk3qNjpQpjymzU1DnofF
    tv6bmLDakFgNhQ6ZCYLA8hYy8NMf1PKqhrdCO821Io+vvtumdCQcuE9vmHGoQHL7
    uyM1RDdeTpgqKdti2wWA2Ij6QavmWHc2nGixnQD30WLfOCfRP5Rfj8+xFxFZABAH
    T8AAt2cUJUOT9qIwUETt9TkCgYEAqvz5qqMO7YHY6HLNwLnoe/EH9GCoL9Q2+yt5
    ay6Jy/p4chrBbrSdAPPO+4CMw7TXtRxA4hBnXVqfMVUta2Qu3DUTPJfNqT+fzGUo
    mUjPbcHzMyezCSkUokqhoNgVeT8ETZ/WJpfxwC3FSAelaBPUP9qB8nHmK314Cb5H
    zHWCadkCgYAm/KK18ZQNLMbG4fLn3Xnv4rxOpae7NoWQlbfzcbqFmDYZK5jHkdeL
    EikedX9nTCUmhC0DXGOwZHAigYx+YNW6haCQ+kUvfF3roYlZ9FNVCWjXQsL9vI4T
    0MUMT0EOPcjMcQLqANTrtFRrjBSC56ajuVc5nSjgdR2JhG9s3fcmKg==
    -----END RSA PRIVATE KEY-----
database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123
  schema: accounts
